@URL = https://web-production-5d34.up.railway.app

########################################################################
########################### PRUEBAS ####################################
########################################################################

###
# Obtener usuarios de prueba

GET {{URL}}/traer_usuarios

###
# Crear usuario de prueba

POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez",
    "provincia": "Buenos Aires"
}

###
# Actualizar usuario de prueba

PUT {{URL}}/actualizar_usuario_prueba/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario de prueba

DELETE {{URL}}/eliminar_usuario_prueba/1

########################################################################
###################### GESTIÓN USUARIOS ################################
########################################################################

###
# Traer usuarios

GET {{URL}}/traer_usuarios_voluntariado

###
# Crear usuario

POST {{URL}}/nuevo_usuario_voluntariado
Content-Type: application/json

{
    "nombre": "Santiago",
    "mail": "santiago.coronel@sagradoalcal.edu.ar",
    "clave": "Voluntario01",
    "perfil": "Referente"
}

###
# Actualizar usuario

PUT {{URL}}/actualizar_usuario_voluntariado/2
Content-Type: application/json

{
    "nombre": "Juan Actualizado",
    "mail": "juan@sagradoalcal.edu.ar",
    "perfil": "Voluntario",
    "clave": "Voluntario123"
}

###
# Activar usuario

PUT {{URL}}/activar_usuario/2

###
# Desactivar usuario

PUT {{URL}}/desactivar_usuario/2

########################################################################
######################## GESTIÓN ANUNCIOS ##############################
########################################################################

###
# Traer anuncios

GET {{URL}}/traer_anuncios

###
# Crear anuncio

POST {{URL}}/nuevo_anuncio
Content-Type: application/json

{
    "titulo": "Colecta de ropa",
    "descripcion": "Traer ropa de invierno",
    "img": "ropa.jpg",
    "fecha_evento": "2026-07-20 17:00:00",
    "tipo_evento": "Solidario",
    "usuario": 1
}

###
# Actualizar anuncio

PUT {{URL}}/actualizar_anuncio/1
Content-Type: application/json

{
    "titulo": "Colecta de alimentos",
    "descripcion": "Traer alimentos no perecederos"
}

###
# Eliminar anuncio

DELETE {{URL}}/eliminar_anuncio/1

########################################################################
######################## GESTIÓN INVENTARIO ############################
########################################################################

###
# Añadir objeto

POST {{URL}}/nuevo_objeto
Content-Type: application/json

{
    "nombre": "Leche",
    "cantidad": 20
}

###
# Traer inventario

GET {{URL}}/traer_inventario

###
# Actualizar objeto

PUT {{URL}}/actualizar_objeto/1
Content-Type: application/json

{
    "cantidad": 30
}

###
# Eliminar objeto

DELETE {{URL}}/eliminar_objeto/1

########################################################################
###################### GESTIÓN DESTINATARIOS ###########################
########################################################################

###
# Registrar destinatario

POST {{URL}}/nuevo_destinatario
Content-Type: application/json

{
    "nombres": "Juan",
    "apellidos": "Perez",
    "dni": 45111222,
    "fecha_nacimiento": "2015-08-12",
    "domicilio": "Calle 123",
    "escuela_anio": "4°",
    "retirar_solo": 0,
    "adulto_responsable_uno": "Maria Perez",
    "adulto_responsable_dos": "Carlos Perez",
    "personas_autorizadas_retiro": "Ana Gomez",
    "quien_vive": "Padres",
    "condicion_salud": "Ninguna"
}

###
# Traer destinatarios

GET {{URL}}/traer_destinatarios

###
# Actualizar destinatario

PUT {{URL}}/actualizar_destinatario/45111222
Content-Type: application/json

{
    "domicilio": "Calle 456",
    "escuela_anio": "5°",
    "retirar_solo": 1
}

###
# Eliminar destinatario

DELETE {{URL}}/eliminar_destinatario/45111222


########################################################################
######################## GESTIÓN PROYECTOS ##############################

###
# Agregar proyecto

POST {{URL}}/nuevo_proyecto
Content-Type: application/json

{
    "nombre": "Merendero"
}

###
# Traer proyectos

GET {{URL}}/traer_proyectos

###
# Actualizar proyecto

PUT {{URL}}/actualizar_proyecto/1
Content-Type: application/json

{
    "nombre": "Boomerang"
}

###
# Eliminar proyecto

DELETE {{URL}}/eliminar_proyecto/4


########################################################################
############### DESTINATARIOS - PROYECTOS ###############################

###
# Asignar destinatario a un proyecto

POST {{URL}}/asignar_destinatario_proyecto
Content-Type: application/json

{
    "destinatarios_dni": 45111222,
    "proyectos_idproyecto": 1
}

###
# Traer destinatarios del proyecto (solo nombre y DNI)

GET {{URL}}/traer_destinatarios_proyecto/1

###
# Traer un destinatario por DNI (ficha completa)

GET {{URL}}/traer_destinatario/45111222

###
# Actualizar asignación

PUT {{URL}}/actualizar_destinatario_proyecto/1
Content-Type: application/json

{
    "proyectos_idproyecto": 2
}

###
# Eliminar asignación

DELETE {{URL}}/eliminar_destinatario_proyecto/1