@URL = https://web-production-5d34.up.railway.app

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez",
    "provincia": "Buenos Aires"
}


###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario_prueba/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario_prueba/3






#####################################################################
####################### LINEAS VOLUNTARIADO ###########################

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios_voluntariado

###
# Crear usuario
POST {{URL}}/nuevo_usuario_voluntariado
Content-Type: application/json

{
    "nombre": "Santiago",
    "mail": "santiago.coronel@sagradoalcal.edu.ar",
    "clave": "Voluntario01",
    "perfil": "Referente"
}

###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario_voluntariado/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario_voluntariado/3